required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "knative.dev/pkg/codegen/cmd/injection-gen",
]

[prune]
  go-tests = true
  unused-packages = true

# Direct dependencies
[[constraint]]
  name = "knative.dev/pkg"
  branch = "release-0.9"

[[constraint]]
  name = "knative.dev/serving"
  version = "v0.9.0"
  
[[constraint]]
  name = "github.com/cloudevents/sdk-go"
  version = "0.10.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.1"

# Transitive dependencies of knative.dev/pkg
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.9"
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.9"
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.9"
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.9"
[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.9"
