# Copyright 2019 The Kyma Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: mqttsource-controller
  namespace: mqtt-source
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mqttsource-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  # Source resources and statuses we care about.
  - apiGroups:
      - sources.kyma-project.io
    resources:
      - mqttsources
    verbs:
      - list
      - watch
  - apiGroups:
      - sources.kyma-project.io
    resources:
      - mqttsources/status
    verbs:
      - update
  # Knative Services
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - list
      - watch
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mqttsource-controller
subjects:
  - kind: ServiceAccount
    name: mqttsource-controller
    namespace: mqtt-source
roleRef:
  kind: ClusterRole
  name: mqttsource-controller
  apiGroup: rbac.authorization.k8s.io
